create table if not exists public.daily_updates (
  id bigint generated by default as identity primary key,
  festival_day integer unique not null check (festival_day between 1 and 9),
  title text not null,
  summary text not null,
  media_url text,
  updated_at timestamptz default now()
);
create table if not exists public.puja_details (
  id bigint generated by default as identity primary key,
  festival_day integer unique not null check (festival_day between 1 and 9),
  puja_name text not null,
  fun_activity text not null,
  updated_at timestamptz default now()
);
create table if not exists public.festival_credits (
  id integer primary key default 1,
  priest_name text not null,
  decoration_name text not null,
  lighting_name text not null,
  updated_at timestamptz default now()
);
alter table public.daily_updates enable row level security;
alter table public.puja_details enable row level security;
alter table public.festival_credits enable row level security;
create policy "public reads daily updates" on public.daily_updates for select using (true);
create policy "public reads puja details" on public.puja_details for select using (true);
create policy "public reads credits" on public.festival_credits for select using (true);
create policy "admins manage daily updates" on public.daily_updates for all to authenticated using (true) with check (true);
create policy "admins manage puja details" on public.puja_details for all to authenticated using (true) with check (true);
create policy "admins manage credits" on public.festival_credits for all to authenticated using (true) with check (true);
insert into storage.buckets (id,name,public) values ('festival-media','festival-media',true) on conflict (id) do update set public=true;
create policy "public reads festival media" on storage.objects for select using (bucket_id='festival-media');
create policy "admins upload festival media" on storage.objects for insert to authenticated with check (bucket_id='festival-media');

-- Payment receipts are insert-only for visitors. Full records (including UTR and
-- contact details) are visible only to authenticated festival administrators.
create table if not exists public.payment_receipts (
  id bigint generated by default as identity primary key,
  public_reference text unique not null check (char_length(public_reference) between 10 and 40),
  donor_name text not null check (char_length(donor_name) between 2 and 120),
  mobile text not null check (mobile ~ '^[0-9]{10}$'),
  email text,
  gotra text,
  amount numeric(10,2) not null check (amount > 0 and amount <= 100000),
  utr text unique not null check (utr ~ '^[0-9]{12}$'),
  status text not null default 'pending' check (status in ('pending','verified','rejected')),
  verified_by uuid references auth.users(id),
  verified_at timestamptz,
  created_at timestamptz not null default now()
);
alter table public.payment_receipts enable row level security;
create policy "visitors submit payment receipts" on public.payment_receipts for insert to anon with check (status = 'pending' and verified_by is null and verified_at is null);
create policy "admins read payment receipts" on public.payment_receipts for select to authenticated using (true);
create policy "admins verify payment receipts" on public.payment_receipts for update to authenticated using (true) with check (status in ('pending','verified','rejected'));
create index if not exists payment_receipts_status_created_idx on public.payment_receipts(status,created_at desc);

-- Returns only non-sensitive status fields for a donor's high-entropy reference.
create or replace function public.get_payment_status(lookup_reference text)
returns table(public_reference text,status text,amount numeric,verified_at timestamptz)
language sql security definer set search_path = public
as $$ select p.public_reference,p.status,p.amount,p.verified_at from public.payment_receipts p where p.public_reference=lookup_reference limit 1 $$;
revoke all on function public.get_payment_status(text) from public;
grant execute on function public.get_payment_status(text) to anon,authenticated;
