create table if not exists public.daily_updates (
  id bigint generated by default as identity primary key,
  festival_day integer unique not null check (festival_day between 1 and 9),
  title text not null,
  summary text not null,
  media_url text,
  updated_at timestamptz default now()
);
create table if not exists public.puja_details (
  id bigint generated by default as identity primary key,
  festival_day integer unique not null check (festival_day between 1 and 9),
  puja_name text not null,
  fun_activity text not null,
  updated_at timestamptz default now()
);
create table if not exists public.festival_credits (
  id integer primary key default 1,
  priest_name text not null,
  decoration_name text not null,
  lighting_name text not null,
  updated_at timestamptz default now()
);
alter table public.daily_updates enable row level security;
alter table public.puja_details enable row level security;
alter table public.festival_credits enable row level security;
create policy "public reads daily updates" on public.daily_updates for select using (true);
create policy "public reads puja details" on public.puja_details for select using (true);
create policy "public reads credits" on public.festival_credits for select using (true);
create policy "admins manage daily updates" on public.daily_updates for all to authenticated using (true) with check (true);
create policy "admins manage puja details" on public.puja_details for all to authenticated using (true) with check (true);
create policy "admins manage credits" on public.festival_credits for all to authenticated using (true) with check (true);
insert into storage.buckets (id,name,public) values ('festival-media','festival-media',true) on conflict (id) do update set public=true;
create policy "public reads festival media" on storage.objects for select using (bucket_id='festival-media');
create policy "admins upload festival media" on storage.objects for insert to authenticated with check (bucket_id='festival-media');
