import {neon} from '@neondatabase/serverless';
import type {FestivalContent} from '@/backend/festival-content';

function database(){
 const url=process.env.DATABASE_URL;
 return url?neon(url):null;
}

export async function ensureNeonSchema(){
 const sql=database();
 if(!sql)return null;
 await sql`create table if not exists festival_content (
  section text primary key check (section in ('gallery','bhavani','accounts','nightPrograms')),
  payload jsonb not null default '[]'::jsonb,
  updated_at timestamptz not null default now()
 )`;
 await sql`create table if not exists payment_receipts (
  id bigint generated by default as identity primary key,
  public_reference text unique not null,
  donor_name text not null,
  mobile text not null,
  amount numeric(10,2) not null check (amount > 0 and amount <= 100000),
  utr text,
  status text not null default 'pending' check (status in ('pending','verified','rejected')),
  created_at timestamptz not null default now()
 )`;
 return sql;
}

export async function readNeonContent(){
 const sql=await ensureNeonSchema();
 if(!sql)return null;
 const rows=await sql.query('select section,payload from festival_content',[],{fetchOptions:{cache:'no-store'}});
 return rows.reduce<Record<string,unknown>>((content,row)=>({...content,[String(row.section)]:row.payload}),{});
}

export async function writeNeonSection<K extends keyof FestivalContent>(section:K,payload:FestivalContent[K]){
 const sql=await ensureNeonSchema();
 if(!sql)return false;
 await sql.query('insert into festival_content(section,payload,updated_at) values($1,$2::jsonb,now()) on conflict(section) do update set payload=excluded.payload,updated_at=now()',[section,JSON.stringify(payload)]);
 return true;
}

export type PaymentRecord={public_reference:string;donor_name:string;mobile:string;amount:number;utr:string|null};
export async function createNeonPayment(record:PaymentRecord){
 const sql=await ensureNeonSchema();
 if(!sql)return false;
 await sql.query('insert into payment_receipts(public_reference,donor_name,mobile,amount,utr) values($1,$2,$3,$4,$5)',[record.public_reference,record.donor_name,record.mobile,record.amount,record.utr]);
 return true;
}
