'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {ArrowLeft,CalendarDays,ImagePlus,LayoutDashboard,Loader2,LogIn,LogOut,Save,ShieldCheck,Upload,Users} from 'lucide-react';
import {supabase} from '@/lib/supabase';

export default function AdminPage(){
 const [email,setEmail]=useState(''),[sent,setSent]=useState(false),[loading,setLoading]=useState(false),[session,setSession]=useState<any>(null),[tab,setTab]=useState('Media');
 useEffect(()=>{supabase?.auth.getSession().then(({data})=>setSession(data.session));const sub=supabase?.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>sub?.data.subscription.unsubscribe()},[]);
 const login=async(e:React.FormEvent)=>{e.preventDefault();setLoading(true);if(supabase){await supabase.auth.signInWithOtp({email,options:{emailRedirectTo:`${location.origin}/admin`}});setSent(true)}else setSent(true);setLoading(false)};
 if(!session&&!sent)return <main className="admin-login"><Link href="/"><ArrowLeft/>Back to website</Link><section><span><ShieldCheck/></span><p>ORGANIZER PORTAL</p><h1>Temple Administration</h1><small>Secure access for authorized committee members.</small><form onSubmit={login}><label>Email address<input type="email" required value={email} onChange={e=>setEmail(e.target.value)} placeholder="organizer@example.com"/></label><button disabled={loading}>{loading?<Loader2 className="spin"/>:<LogIn/>}Send secure sign-in link</button></form><em>{supabase?'Supabase passwordless authentication is active.':'Demo mode: add Supabase keys in .env.local to enable authentication.'}</em></section></main>;
 if(sent&&!session)return <main className="admin-login"><section><span><ShieldCheck/></span><h1>Check your inbox</h1><small>{supabase?`A secure sign-in link was sent to ${email}.`:'The interface is ready. Connect Supabase to send real sign-in links.'}</small><Link className="admin-back" href="/">Return to festival website</Link></section></main>;
 return <main className="admin-shell"><aside><Link className="admin-brand" href="/"><span>శ్రీ</span><b>Durga Devi<br/><small>ADMIN PORTAL</small></b></Link><nav><button className="active"><LayoutDashboard/>Dashboard</button><button><ImagePlus/>Media Library</button><button><Users/>Gootra Directory</button><button><CalendarDays/>Events & Banners</button></nav><button onClick={()=>supabase?.auth.signOut()}><LogOut/>Sign out</button></aside><div className="admin-main"><header><div><p>Festival Management</p><h1>Namaste, Organizer</h1></div><span><i/>Supabase connected</span></header><div className="admin-stats"><article><ImagePlus/><span><small>Gallery items</small><b>24</b></span></article><article><Users/><span><small>Devotee records</small><b>128</b></span></article><article><CalendarDays/><span><small>Scheduled events</small><b>9</b></span></article></div><section className="admin-panel"><div className="admin-tabs">{['Media','Gootra List','Events'].map(x=><button key={x} onClick={()=>setTab(x)} className={tab===x?'active':''}>{x}</button>)}</div><div className="admin-toolbar"><div><h2>{tab}</h2><p>Changes publish to the public festival portal.</p></div><button><Save/>Save changes</button></div>{tab==='Media'?<div className="upload-zone"><Upload/><h3>Upload daily photos & videos</h3><p>Drag files here or choose from your device. JPG, PNG, WebP and MP4.</p><button>Choose files</button></div>:tab==='Gootra List'?<div className="admin-empty"><Users/><h3>Devotee directory editor</h3><p>Add, edit and approve devotee records from your Supabase table.</p><button>Add devotee</button></div>:<div className="admin-empty"><CalendarDays/><h3>Festival timetable editor</h3><p>Update event timing, category and public banner status.</p><button>Add event</button></div>}</section></div></main>
}
