'use client';
import {useEffect,useMemo,useState} from 'react';
import {QRCodeCanvas} from 'qrcode.react';
import {ArrowUpRight,CalendarDays,Camera,Check,ChevronRight,Clock,Download,Facebook,Heart,Home,Image as ImageIcon,Instagram,Languages,MapPin,Menu,Music2,Phone,Play,Search,Share2,Sparkles,Users,Video,X} from 'lucide-react';

type Lang='te'|'en';
const copy={
  en:{brand:'Sri Durga Devi',place:'Sharannavaratri Mahotsavam · Koragam',nav:['Home','Events','Pujas','Gallery','Donors','Contact'],eyebrow:'Koragam village presents',title:'Nine sacred nights. One divine celebration.',desc:'Join our community for daily alankaram, Vedic pujas, cultural evenings and the blessings of Sri Durga Devi.',book:'Book Puja / Seva',donate:'Donate now',count:'Mahotsavam begins in',days:'Days',hours:'Hours',mins:'Minutes',secs:'Seconds',events:'Festival Timetable',eventsSub:'Nine days of devotion, culture and community',gallery:'Sacred Moments',gallerySub:'A glimpse of worship, celebration and togetherness',gootra:'Gootra Naamalu',gootraSub:'Devotees, donors and the seva family',seva:'Offer a Seva',sevaSub:'Choose a puja and share your sankalpam',live:'Virtual Darshan',liveSub:'Join evening Harathi and festival streams',committee:'Temple Committee',committeeSub:'Serving the festival with devotion',contact:'Visit Sri Durga Devi',all:'All',photos:'Photos',videos:'Videos',highlights:'2025 Highlights'},
  te:{brand:'శ్రీ దుర్గాదేవి',place:'శరన్నవరాత్రి మహోత్సవములు · కొరగాం',nav:['ముఖ పుట','కార్యక్రమాలు','పూజలు','గ్యాలరీ','దాతలు','సంప్రదించండి'],eyebrow:'కొరగాం గ్రామ ప్రజల సమర్పణ',title:'తొమ్మిది పవిత్ర రాత్రులు. ఒక దివ్య వేడుక.',desc:'ప్రతిరోజూ అమ్మవారి అలంకారం, వేద పూజలు, సాంస్కృతిక కార్యక్రమాలు మరియు శ్రీ దుర్గాదేవి ఆశీస్సులకు స్వాగతం.',book:'పూజ / సేవ బుక్ చేయండి',donate:'విరాళం ఇవ్వండి',count:'మహోత్సవం ప్రారంభానికి',days:'రోజులు',hours:'గంటలు',mins:'నిమిషాలు',secs:'సెకన్లు',events:'ఉత్సవ కార్యక్రమాలు',eventsSub:'తొమ్మిది రోజుల భక్తి, సంస్కృతి మరియు సేవ',gallery:'పవిత్ర క్షణాలు',gallerySub:'పూజలు, వేడుకలు మరియు ఆనందాల దృశ్యాలు',gootra:'గోత్ర నామాలు',gootraSub:'భక్తులు, దాతలు మరియు సేవా బృందం',seva:'సేవ సమర్పించండి',sevaSub:'పూజను ఎంచుకొని మీ సంకల్పం తెలపండి',live:'వర్చువల్ దర్శనం',liveSub:'సాయంత్రం హారతి మరియు ప్రత్యక్ష ప్రసారాలు',committee:'ఆలయ కమిటీ',committeeSub:'భక్తితో ఉత్సవ సేవలో',contact:'శ్రీ దుర్గాదేవిని దర్శించండి',all:'అన్నీ',photos:'ఫోటోలు',videos:'వీడియోలు',highlights:'2025 విశేషాలు'}
};
const events=[
 {day:'Day 01',date:'Oct 11',time:'06:00 AM',title:'Kalasha Sthapana & Panchamrutha Abhishekam',te:'కలశ స్థాపన & పంచామృత అభిషేకం',cat:'Pujas & Rituals'},
 {day:'Day 03',date:'Oct 13',time:'06:30 PM',title:'Sahasra Deepalankarana',te:'సహస్ర దీపాలంకరణ',cat:'Pujas & Rituals'},
 {day:'Day 05',date:'Oct 15',time:'09:00 AM',title:'Rudrabhishekam',te:'రుద్రాభిషేకం',cat:'Pujas & Rituals'},
 {day:'Day 06',date:'Oct 16',time:'05:00 PM',title:'Children’s Cultural Evening & Games',te:'బాలల సాంస్కృతిక కార్యక్రమాలు & ఆటలు',cat:'Cultural & Games'},
 {day:'Day 08',date:'Oct 18',time:'07:00 PM',title:'108 Harathulu',te:'108 హారతులు',cat:'Special Services'},
 {day:'Day 09',date:'Oct 19',time:'12:00 PM',title:'Maha Annadanam',te:'మహా అన్నదానం',cat:'Special Services'},
 {day:'Day 10',date:'Oct 20',time:'04:00 PM',title:'Nimajjanam Procession',te:'నిమజ్జన మహోత్సవం',cat:'Cultural & Games'}
];
const gallery=[
 {src:'/img1.jpg',type:'Photos',year:true,title:'Ammavari Alankaram'}, {src:'/img2.jpg',type:'Photos',year:true,title:'Sacred Puja'},
 {src:'/img3.jpg',type:'Photos',year:false,title:'Festival Gathering'}, {src:'/img4.jpg',type:'Photos',year:true,title:'Divine Darshan'},
 {src:'/p.mp4',type:'Videos',year:true,title:'Evening Harathi'}, {src:'/bajana.mp4',type:'Videos',year:false,title:'Bhajana Seva'}
];
const donors=[
 ['1','S. Appala Naidu','Bharadwaja','ప్రధాన దాతలు','+91 98765 43210'],['2','K. Lakshmi','Kashyapa','ప్రధాన దాతలు','+91 98660 12457'],['3','P. Srinivasa Rao','Vasishta','సేవా బృందం','+91 98481 77654'],['4','G. Devi','Gautama','సేవా బృందం','+91 97041 23568'],['5','M. Ramakrishna','Koundinya','ప్రధాన దాతలు','+91 94920 87654']
];
const sevas=[['Panchamrutha Abhishekam','పంచామృత అభిషేకం',501],['Kumkumarchana','కుంకుమార్చన',251],['Sahasra Deepalankarana','సహస్ర దీపాలంకరణ',1101],['Annadanam Sponsorship','అన్నదాన సేవ',5001]];
const committee=[['/profile.jpg','S. Simhachalam','President','అధ్యక్షులు'],['/dep1.jpg','V. Satyanarayana','Chief Priest','ప్రధాన అర్చకులు'],['/dep2.jpg','K. Govinda Rao','Festival Coordinator','ఉత్సవ సమన్వయకర్త']];

export default function FestivalApp(){
 const [lang,setLang]=useState<Lang>('te'),[menu,setMenu]=useState(false),[eventTab,setEventTab]=useState('All'),[galleryTab,setGalleryTab]=useState('All'),[lightbox,setLightbox]=useState<typeof gallery[0]|null>(null),[modal,setModal]=useState<'seva'|'donate'|null>(null),[selected,setSelected]=useState(sevas[0]),[receipt,setReceipt]=useState(''),[search,setSearch]=useState('');
 const t=copy[lang]; const target=useMemo(()=>new Date('2027-10-01T06:00:00+05:30'),[]); const [left,setLeft]=useState({d:0,h:0,m:0,s:0});
 useEffect(()=>{const tick=()=>{const x=Math.max(0,target.getTime()-Date.now());setLeft({d:Math.floor(x/86400000),h:Math.floor(x/3600000)%24,m:Math.floor(x/60000)%60,s:Math.floor(x/1000)%60})};tick();const i=setInterval(tick,1000);return()=>clearInterval(i)},[target]);
 const filteredEvents=eventTab==='All'?events:events.filter(e=>e.cat===eventTab); const filteredGallery=gallery.filter(g=>galleryTab==='All'||g.type===galleryTab||(galleryTab==='2025 Highlights'&&g.year)); const filteredDonors=donors.filter(d=>d.join(' ').toLowerCase().includes(search.toLowerCase()));
 const upi=process.env.NEXT_PUBLIC_TEMPLE_UPI_ID||'temple@upi'; const qr=`upi://pay?pa=${upi}&pn=Sri%20Durga%20Devi%20Temple&cu=INR`;
 const go=(id:string)=>{document.getElementById(id)?.scrollIntoView({behavior:'smooth'});setMenu(false)};
 const exportDoc=()=>{const html=`<html><body><h1>Sri Durga Devi Temple, Koragam</h1><h3>Gootra Naamalu</h3>${document.getElementById('gootra-table')?.outerHTML}</body></html>`;const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([html],{type:'application/msword'}));a.download='koragam-gootra-naamalu.doc';a.click()};
 const exportPdf=()=>{window.print()};
 const share=async()=>{if(navigator.share)await navigator.share({title:lightbox?.title,url:location.href});else await navigator.clipboard.writeText(location.href)};
 return <main>
  <header className="header"><button className="brand" onClick={()=>go('home')}><span className="brand-mark">శ్రీ</span><span><b>{t.brand}</b><small>{t.place}</small></span></button><nav>{t.nav.map((n,i)=><button key={n} onClick={()=>go(['home','events','sevas','gallery','donors','contact'][i])}>{n}</button>)}</nav><div className="header-actions"><button className="language" onClick={()=>setLang(lang==='te'?'en':'te')}><Languages size={17}/>{lang==='te'?'English':'తెలుగు'}</button><button className="menu" onClick={()=>setMenu(!menu)} aria-label="Menu">{menu?<X/>:<Menu/>}</button></div>{menu&&<div className="mobile-menu">{t.nav.map((n,i)=><button key={n} onClick={()=>go(['home','events','sevas','gallery','donors','contact'][i])}>{n}<ChevronRight size={16}/></button>)}</div>}</header>
  <section id="home" className="hero"><video autoPlay muted loop playsInline poster="/home.jpg"><source src="/vid6.mp4" type="video/mp4"/></video><div className="hero-overlay"/><div className="hero-pattern"/><div className="hero-content"><div className="eyebrow"><Sparkles size={15}/>{t.eyebrow}</div><p className="festival-date"><CalendarDays size={17}/> 11–20 October 2027 · Koragam</p><h1>{t.title}</h1><p className="hero-copy">{t.desc}</p><div className="hero-ctas"><button className="btn gold" onClick={()=>setModal('seva')}>{t.book}<ChevronRight size={18}/></button><button className="btn outline" onClick={()=>setModal('donate')}><Heart size={18}/>{t.donate}</button></div></div><div className="countdown"><p>{t.count}</p><div>{([[left.d,t.days],[left.h,t.hours],[left.m,t.mins],[left.s,t.secs]] as [number,string][]).map(([v,l])=><span key={l}><b>{String(v).padStart(2,'0')}</b><small>{l}</small></span>)}</div></div></section>
  <section className="quick-strip"><button onClick={()=>go('events')}><CalendarDays/><span><b>{lang==='te'?'నేటి కార్యక్రమాలు':'Today’s Events'}</b><small>View schedule</small></span></button><button onClick={()=>setModal('seva')}><Sparkles/><span><b>{lang==='te'?'పూజ బుకింగ్':'Book a Puja'}</b><small>Offer your sankalpam</small></span></button><button onClick={()=>go('live')}><Play/><span><b>{lang==='te'?'ప్రత్యక్ష దర్శనం':'Live Darshan'}</b><small>Evening Harathi</small></span></button><a href="tel:+919876543210"><Phone/><span><b>{lang==='te'?'ఆలయానికి కాల్ చేయండి':'Call the Temple'}</b><small>+91 98765 43210</small></span></a></section>
  <SectionHeading kicker="2027 MAHOTSAVAM" title={t.events} sub={t.eventsSub}/><section id="events" className="section events-section"><Tabs values={['All','Pujas & Rituals','Cultural & Games','Special Services']} active={eventTab} set={setEventTab}/><div className="timeline">{filteredEvents.map((e,i)=><article className="event-card" key={e.title}><div className="event-date"><span>{e.day}</span><b>{e.date}</b></div><div className="event-dot"/><div className="event-info"><small><Clock size={14}/>{e.time} · {e.cat}</small><h3>{lang==='te'?e.te:e.title}</h3><p>{lang==='te'?e.title:e.te}</p></div>{i===0&&<span className="featured">Opening</span>}</article>)}</div></section>
  <section id="sevas" className="section seva-wrap"><div><span className="section-kicker">SEVA & SANKALPAM</span><h2>{t.seva}</h2><p>{t.sevaSub}</p><div className="seva-grid">{sevas.map(s=><button className={`seva-card ${selected[0]===s[0]?'selected':''}`} key={s[0]} onClick={()=>{setSelected(s);setModal('seva')}}><span className="seva-icon"><Sparkles/></span><span><b>{lang==='te'?s[1]:s[0]}</b><small>{lang==='te'?s[0]:s[1]}</small></span><strong>₹{s[2]}</strong></button>)}</div></div><div className="donation-card"><div className="donation-top"><Heart/><span>{lang==='te'?'అమ్మవారి సేవకు మీ వంతు సహాయం':'Support Amma’s sacred celebrations'}</span></div><h3>{lang==='te'?'దైవ సేవలో భాగస్వాములు కండి':'Every offering becomes a blessing'}</h3><p>{lang==='te'?'అన్నదానం, పుష్పాలంకరణ మరియు ఉత్సవ నిర్వహణకు విరాళం ఇవ్వండి.':'Contribute toward Annadanam, floral decorations and festival arrangements.'}</p><button className="btn cream" onClick={()=>setModal('donate')}>{t.donate}<Heart size={18}/></button></div></section>
  <SectionHeading kicker="PHOTO & VIDEO ARCHIVE" title={t.gallery} sub={t.gallerySub}/><section id="gallery" className="section"><Tabs values={['All','Photos','Videos','2025 Highlights']} active={galleryTab} set={setGalleryTab}/><div className="gallery-grid">{filteredGallery.map((g,i)=><button className={`gallery-item g${i}`} key={g.src} onClick={()=>setLightbox(g)}>{g.type==='Videos'?<video muted preload="metadata" src={g.src}/>:<img src={g.src} alt={g.title}/>}<span className="gallery-shade"/><span className="media-type">{g.type==='Videos'?<Play/>:<Camera/>}</span><span className="gallery-label"><b>{g.title}</b><small>{g.type} · Koragam</small></span></button>)}</div></section>
  <section id="live" className="live-section"><div className="section"><div className="live-copy"><span className="live-pill"><i/> LIVE FROM KORAGAM</span><h2>{t.live}</h2><p>{t.liveSub}</p><div className="broadcast"><span><CalendarDays/>Daily during Navaratri</span><span><Clock/>6:30 PM onwards</span></div><a className="btn gold" href="https://youtube.com" target="_blank" rel="noreferrer"><Play size={18}/>Watch on YouTube</a></div><div className="video-frame"><video controls poster="/img4.jpg" src="/vid3.mp4"/><span className="live-tag"><i/> FESTIVAL REPLAY</span></div></div></section>
  <SectionHeading kicker="DEVOTEE DIRECTORY" title={t.gootra} sub={t.gootraSub}/><section id="donors" className="section donors"><div className="table-tools"><label><Search/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search name or gootram…"/></label><div><button onClick={exportPdf}><Download/>Export PDF</button><button onClick={exportDoc}><Download/>Export Word (.doc)</button></div></div><div className="table-scroll"><table id="gootra-table"><thead><tr><th>S.No</th><th>Name (పేరు)</th><th>Gootram (గోత్రం)</th><th>Category</th><th>Phone</th></tr></thead><tbody>{filteredDonors.map(d=><tr key={d[0]}>{d.map((x,i)=><td key={x}>{i===3?<span className="category">{x}</span>:i===4?<a href={`tel:${x.replaceAll(' ','')}`}>{x}</a>:x}</td>)}</tr>)}</tbody></table></div><p className="privacy-note">Phone numbers shown are sample data. Enable Supabase and organizer-approved records before publishing.</p></section>
  <section className="committee-section"><SectionHeading kicker="OUR SEVA FAMILY" title={t.committee} sub={t.committeeSub}/><div className="section committee-grid">{committee.map(c=><article key={c[1]}><img src={c[0]} alt={c[1]}/><div><h3>{c[1]}</h3><p>{lang==='te'?c[3]:c[2]}</p><small>{lang==='te'?c[2]:c[3]}</small></div><a href="tel:+919876543210" aria-label={`Call ${c[1]}`}><Phone/></a></article>)}</div></section>
  <section id="contact" className="contact-section"><div className="contact-copy"><span className="section-kicker">DARSHAN & DIRECTIONS</span><h2>{t.contact}</h2><p><MapPin/>Sri Durga Devi Temple, Koragam Village, Andhra Pradesh</p><p><Clock/>Morning 5:30–11:30 · Evening 5:00–9:30</p><div><a className="btn gold" href="https://maps.google.com/?q=Koragam+Andhra+Pradesh" target="_blank"><MapPin/>Get directions</a><a className="btn outline" href="tel:+919876543210"><Phone/>Call now</a></div></div><div className="map-card"><MapPin/><b>Koragam</b><span>Andhra Pradesh</span></div></section>
  <footer><div className="brand"><span className="brand-mark">శ్రీ</span><span><b>{t.brand}</b><small>{t.place}</small></span></div><p>© 2027 Sri Durga Devi Sharannavaratri Mahotsavam Committee</p><div><a href="#"><Facebook/></a><a href="#"><Instagram/></a><a href="#"><Video/></a></div></footer>
  <nav className="bottom-nav"><button onClick={()=>go('home')}><Home/><span>Home</span></button><button onClick={()=>go('events')}><CalendarDays/><span>Events</span></button><button onClick={()=>go('sevas')}><Sparkles/><span>Pujas</span></button><button onClick={()=>go('gallery')}><ImageIcon/><span>Gallery</span></button><button onClick={()=>go('contact')}><Phone/><span>Contact</span></button></nav>
  {lightbox&&<div className="modal lightbox" onClick={()=>setLightbox(null)}><button className="close" aria-label="Close"><X/></button><div onClick={e=>e.stopPropagation()}>{lightbox.type==='Videos'?<video controls autoPlay src={lightbox.src}/>:<img src={lightbox.src} alt={lightbox.title}/>}<div><span><b>{lightbox.title}</b><small>Durga Devi Mahotsavam · Koragam</small></span><button onClick={share}><Share2/>Share</button></div></div></div>}
  {modal&&<ActionModal type={modal} close={()=>{setModal(null);setReceipt('')}} lang={lang} selected={selected} setSelected={setSelected} qr={qr} receipt={receipt} setReceipt={setReceipt}/>} 
 </main>
}
function SectionHeading({kicker,title,sub}:{kicker:string,title:string,sub:string}){return <div className="section-heading"><span>{kicker}</span><h2>{title}</h2><p>{sub}</p><i/></div>}
function Tabs({values,active,set}:{values:string[],active:string,set:(x:string)=>void}){return <div className="tabs">{values.map(v=><button className={active===v?'active':''} key={v} onClick={()=>set(v)}>{v}</button>)}</div>}
function ActionModal({type,close,lang,selected,setSelected,qr,receipt,setReceipt}:{type:'seva'|'donate',close:()=>void,lang:Lang,selected:(string|number)[],setSelected:(x:any)=>void,qr:string,receipt:string,setReceipt:(x:string)=>void}){const [name,setName]=useState(''),[phone,setPhone]=useState(''),[amount,setAmount]=useState(type==='seva'?String(selected[2]):'501');const submit=(e:React.FormEvent)=>{e.preventDefault();setReceipt(`DDK-${Date.now().toString().slice(-8)}`)};return <div className="modal action-modal"><div className="action-sheet"><button className="close" onClick={close}><X/></button>{receipt?<div className="success"><span><Check/></span><h2>{lang==='te'?'మీ అభ్యర్థన నమోదైంది':'Request registered'}</h2><p>{lang==='te'?'చెల్లింపు చేసిన తరువాత రసీదు నంబర్‌ను భద్రపరచండి.':'Complete the UPI payment and keep this receipt reference.'}</p><div className="receipt"><small>RECEIPT REFERENCE</small><b>{receipt}</b><span>{name} · ₹{amount}</span></div><button className="btn red" onClick={()=>window.print()}><Download/>Print receipt</button></div>:<><span className="section-kicker">{type==='seva'?'ONLINE SEVA':'UPI DONATION'}</span><h2>{type==='seva'?(lang==='te'?'పూజ / సేవ బుకింగ్':'Book Puja / Seva'):(lang==='te'?'విరాళం సమర్పించండి':'Make an offering')}</h2>{type==='donate'&&<div className="qr-card"><QRCodeCanvas value={`${qr}&am=${amount}`} size={150} level="H"/><span>Scan with any UPI app</span></div>}<form onSubmit={submit}>{type==='seva'&&<label>Seva<select value={selected[0]} onChange={e=>setSelected(sevas.find(s=>s[0]===e.target.value)||sevas[0])}>{sevas.map(s=><option key={s[0]} value={s[0]}>{lang==='te'?s[1]:s[0]} · ₹{s[2]}</option>)}</select></label>}<div className="form-row"><label>Devotee name<input required value={name} onChange={e=>setName(e.target.value)} placeholder="Full name"/></label><label>Phone number<input required pattern="[0-9]{10}" value={phone} onChange={e=>setPhone(e.target.value)} placeholder="10-digit number"/></label></div>{type==='seva'&&<label>Gootram<input placeholder="Gootram / గోత్రం"/></label>}<label>Amount (₹)<input type="number" min="1" required value={type==='seva'?String(selected[2]):amount} readOnly={type==='seva'} onChange={e=>setAmount(e.target.value)}/></label><button className="btn red" type="submit">{type==='seva'?'Continue to payment':'Generate payment receipt'}<ArrowUpRight/></button></form><small className="safe-note">Secure UPI payment · Organizer confirms booking after payment verification</small></>}</div></div>}
