'use client';
import {useEffect,useMemo,useState} from 'react';
import {CalendarDays,Camera,ChevronRight,Clock,Download,Facebook,Flower2,Home,Image as ImageIcon,Instagram,Languages,Lightbulb,MapPin,Menu,Phone,Play,Search,Share2,Sparkles,Star,Users,Video,X} from 'lucide-react';
type Lang='te'|'en';
const copy={en:{brand:'Sri Durga Devi',place:'Sharannavaratri Mahotsavam · Koragam',nav:['Home','9 Days','Gallery','Donors','Team','Contact'],eyebrow:'Koragam village presents',title:'Nine sacred days. One divine celebration.',desc:'From October 11, join our village for daily alankaram, Vedic pujas, joyful games and the blessings of Sri Durga Devi.',schedule:'Explore 9-day schedule',count:'Mahotsavam begins in',dayCount:'Nine-day celebration',days:'Days',hours:'Hours',mins:'Minutes',secs:'Seconds',events:'Nine Days of Shakti',eventsSub:'Every day brings a new alankaram, sacred puja and joyful community activity',gallery:'2025 Festival Highlights',gallerySub:'Every photo and video below is from last year’s celebrations',gootra:'Gootra Naamalu',gootraSub:'Devotees, donors and the seva family',committee:'Festival Seva Team',committeeSub:'The people behind every prayer, flower and light',contact:'Visit Sri Durga Devi'},te:{brand:'శ్రీ దుర్గాదేవి',place:'శరన్నవరాత్రి మహోత్సవములు · కొరగాం',nav:['ముఖ పుట','9 రోజులు','గ్యాలరీ','దాతలు','సేవా బృందం','సంప్రదించండి'],eyebrow:'కొరగాం గ్రామ ప్రజల సమర్పణ',title:'తొమ్మిది పవిత్ర రోజులు. ఒక దివ్య వేడుక.',desc:'అక్టోబర్ 11 నుండి ప్రతిరోజూ అమ్మవారి అలంకారం, వేద పూజలు, సరదా ఆటలు మరియు శ్రీ దుర్గాదేవి ఆశీస్సులకు స్వాగతం.',schedule:'9 రోజుల కార్యక్రమాలు',count:'మహోత్సవం ప్రారంభానికి',dayCount:'తొమ్మిది రోజుల మహోత్సవం',days:'రోజులు',hours:'గంటలు',mins:'నిమిషాలు',secs:'సెకన్లు',events:'తొమ్మిది రోజుల శక్తి',eventsSub:'ప్రతిరోజూ కొత్త అలంకారం, పవిత్ర పూజ మరియు ఆనందకరమైన కార్యక్రమం',gallery:'2025 ఉత్సవ విశేషాలు',gallerySub:'క్రింద ఉన్న ఫోటోలు మరియు వీడియోలు గత సంవత్సరం వేడుకలవి',gootra:'గోత్ర నామాలు',gootraSub:'భక్తులు, దాతలు మరియు సేవా బృందం',committee:'ఉత్సవ సేవా బృందం',committeeSub:'ప్రతి పూజ, పువ్వు మరియు వెలుగు వెనుక ఉన్న సేవామూర్తులు',contact:'శ్రీ దుర్గాదేవిని దర్శించండి'}};
const festival=[
 {date:'Oct 11',iso:'2026-10-11',deity:'Sri Swarna Kavacha Durga',te:'శ్రీ స్వర్ణ కవచ దుర్గాదేవి',puja:'Kalasha Sthapana & Panchamrutha Abhishekam',pujaTe:'కలశ స్థాపన & పంచామృత అభిషేకం',fun:'Traditional Rangoli Contest',funTe:'సాంప్రదాయ ముగ్గుల పోటీ'},
 {date:'Oct 12',iso:'2026-10-12',deity:'Sri Bala Tripura Sundari',te:'శ్రీ బాలాత్రిపుర సుందరీదేవి',puja:'Kumkumarchana',pujaTe:'కుంకుమార్చన',fun:'Children’s Drawing & Storytelling',funTe:'బాలల చిత్రలేఖనం & కథల పోటీ'},
 {date:'Oct 13',iso:'2026-10-13',deity:'Sri Gayatri Devi',te:'శ్రీ గాయత్రీదేవి',puja:'Sahasra Deepalankarana',pujaTe:'సహస్ర దీపాలంకరణ',fun:'Musical Chairs — Women & Children',funTe:'మ్యూజికల్ చైర్స్ — మహిళలు & పిల్లలు'},
 {date:'Oct 14',iso:'2026-10-14',deity:'Sri Annapurna Devi',te:'శ్రీ అన్నపూర్ణాదేవి',puja:'Special Naivedyam & Archana',pujaTe:'ప్రత్యేక నైవేద్యం & అర్చన',fun:'Lemon & Spoon Race',funTe:'నిమ్మకాయ చెంచా పోటీ'},
 {date:'Oct 15',iso:'2026-10-15',deity:'Sri Lalitha Tripura Sundari',te:'శ్రీ లలితా త్రిపుర సుందరీదేవి',puja:'Rudrabhishekam',pujaTe:'రుద్రాభిషేకం',fun:'Bhakti Antakshari',funTe:'భక్తి అంత్యాక్షరి'},
 {date:'Oct 16',iso:'2026-10-16',deity:'Sri Saraswati Devi',te:'శ్రీ సరస్వతీదేవి',puja:'Vidyarambham & Saraswati Puja',pujaTe:'విద్యారంభం & సరస్వతీ పూజ',fun:'Quiz & Memory Games',funTe:'క్విజ్ & మెమరీ గేమ్స్'},
 {date:'Oct 17',iso:'2026-10-17',deity:'Sri Durga Devi',te:'శ్రీ దుర్గాదేవి',puja:'Durga Homam',pujaTe:'దుర్గా హోమం',fun:'Kabaddi & Tug of War',funTe:'కబడ్డీ & తాడు లాగుడు'},
 {date:'Oct 18',iso:'2026-10-18',deity:'Sri Mahishasura Mardini',te:'శ్రీ మహిషాసుర మర్దినీదేవి',puja:'108 Harathulu',pujaTe:'108 హారతులు',fun:'Devotional Fancy Dress',funTe:'భక్తి వేషధారణ పోటీ'},
 {date:'Oct 19',iso:'2026-10-19',deity:'Sri Raja Rajeshwari Devi',te:'శ్రీ రాజరాజేశ్వరీదేవి',puja:'Maha Annadanam & Nimajjanam',pujaTe:'మహా అన్నదానం & నిమజ్జనం',fun:'Village Cultural Finale',funTe:'గ్రామ సాంస్కృతిక ముగింపు'}];
const gallery=[{src:'/img1.jpg',type:'Photos',title:'Ammavari Alankaram'},{src:'/img2.jpg',type:'Photos',title:'Sacred Puja'},{src:'/img3.jpg',type:'Photos',title:'Festival Gathering'},{src:'/img4.jpg',type:'Photos',title:'Divine Darshan'},{src:'/p.mp4',type:'Videos',title:'Evening Harathi'},{src:'/bajana.mp4',type:'Videos',title:'Bhajana Seva'}];
const donors=[['1','S. Appala Naidu','Bharadwaja','ప్రధాన దాతలు','+91 98765 43210'],['2','K. Lakshmi','Kashyapa','ప్రధాన దాతలు','+91 98660 12457'],['3','P. Srinivasa Rao','Vasishta','సేవా బృందం','+91 98481 77654'],['4','G. Devi','Gautama','సేవా బృందం','+91 97041 23568'],['5','M. Ramakrishna','Koundinya','ప్రధాన దాతలు','+91 94920 87654']];
export default function FestivalApp(){
 const [lang,setLang]=useState<Lang>('te'),[menu,setMenu]=useState(false),[activeDay,setActiveDay]=useState(0),[galleryTab,setGalleryTab]=useState('All'),[lightbox,setLightbox]=useState<typeof gallery[0]|null>(null),[search,setSearch]=useState(''),[remoteUpdates,setRemoteUpdates]=useState<any[]>([]);
 const t=copy[lang],start=useMemo(()=>new Date('2026-10-11T05:30:00+05:30'),[]),end=useMemo(()=>new Date('2026-10-20T00:00:00+05:30'),[]);const [now,setNow]=useState(new Date()),[left,setLeft]=useState({d:0,h:0,m:0,s:0});
 useEffect(()=>{const tick=()=>{const n=new Date();setNow(n);let target=start;if(n>=start&&n<end){const day=Math.floor((n.getTime()-start.getTime())/86400000);target=new Date(`2026-10-${String(12+day).padStart(2,'0')}T00:00:00+05:30`)}if(n>=end)target=end;const x=Math.max(0,target.getTime()-n.getTime());setLeft({d:Math.floor(x/86400000),h:Math.floor(x/3600000)%24,m:Math.floor(x/60000)%60,s:Math.floor(x/1000)%60})};tick();const i=setInterval(tick,1000);return()=>clearInterval(i)},[start,end]);
 useEffect(()=>{const url=process.env.NEXT_PUBLIC_SUPABASE_URL,key=process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;if(!url||!key)return;fetch(`${url}/rest/v1/daily_updates?select=*&order=festival_day.desc`,{headers:{apikey:key,Authorization:`Bearer ${key}`}}).then(r=>r.ok?r.json():[]).then(setRemoteUpdates).catch(()=>{})},[]);
 const phase=now<start?'before':now>=end?'after':'during',currentDay=phase==='during'?Math.min(8,Math.floor((now.getTime()-start.getTime())/86400000)):phase==='after'?8:0,filteredGallery=gallery.filter(g=>galleryTab==='All'||g.type===galleryTab),filteredDonors=donors.filter(d=>d.join(' ').toLowerCase().includes(search.toLowerCase()));
 const go=(id:string)=>{document.getElementById(id)?.scrollIntoView({behavior:'smooth'});setMenu(false)};const exportDoc=()=>{const html=`<html><body><h1>Sri Durga Devi Temple, Koragam</h1><h3>Gootra Naamalu</h3>${document.getElementById('gootra-table')?.outerHTML}</body></html>`;const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([html],{type:'application/msword'}));a.download='koragam-gootra-naamalu.doc';a.click()};const share=async()=>navigator.share?navigator.share({title:lightbox?.title,url:location.href}):navigator.clipboard.writeText(location.href);
 return <main><header className="header"><button className="brand" onClick={()=>go('home')}><span className="brand-mark">శ్రీ</span><span><b>{t.brand}</b><small>{t.place}</small></span></button><nav>{t.nav.map((n,i)=><button key={n} onClick={()=>go(['home','events','gallery','donors','team','contact'][i])}>{n}</button>)}</nav><div className="header-actions"><button className="language" onClick={()=>setLang(lang==='te'?'en':'te')}><Languages size={17}/>{lang==='te'?'English':'తెలుగు'}</button><button className="menu" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></div>{menu&&<div className="mobile-menu">{t.nav.map((n,i)=><button key={n} onClick={()=>go(['home','events','gallery','donors','team','contact'][i])}>{n}<ChevronRight size={16}/></button>)}</div>}</header>
 <section id="home" className="hero festival-hero"><video autoPlay muted loop playsInline poster="/home.jpg"><source src="/vid6.mp4" type="video/mp4"/></video><div className="hero-overlay"/><div className="hero-pattern"/><div className="floating-diyas"><i/><i/><i/></div><div className="hero-content"><div className="eyebrow"><Sparkles size={15}/>{t.eyebrow}</div><p className="festival-date"><CalendarDays size={17}/> 11–19 October 2026 · Koragam</p><h1>{t.title}</h1><p className="hero-copy">{t.desc}</p><div className="hero-ctas"><button className="btn gold" onClick={()=>go('events')}>{t.schedule}<ChevronRight size={18}/></button><button className="btn outline" onClick={()=>go('gallery')}><Play size={18}/>{lang==='te'?'2025 విశేషాలు':'Watch 2025 highlights'}</button></div></div><div className="countdown"><p>{phase==='before'?t.count:phase==='during'?`${t.dayCount} · Day ${currentDay+1}`:(lang==='te'?'మహోత్సవం పూర్తయింది':'Mahotsavam completed')}</p><div>{([[left.d,t.days],[left.h,t.hours],[left.m,t.mins],[left.s,t.secs]] as [number,string][]).map(([v,l])=><span key={l}><b>{String(v).padStart(2,'0')}</b><small>{l}</small></span>)}</div></div></section>
 <section className="quick-strip three"><button onClick={()=>go('events')}><CalendarDays/><span><b>{lang==='te'?'9 రోజుల షెడ్యూల్':'9-day schedule'}</b><small>October 11–19, 2026</small></span></button><button onClick={()=>go('gallery')}><Camera/><span><b>{lang==='te'?'2025 జ్ఞాపకాలు':'2025 memories'}</b><small>Photos & videos</small></span></button><a href="tel:+919876543210"><Phone/><span><b>{lang==='te'?'ఆలయానికి కాల్ చేయండి':'Call the Temple'}</b><small>+91 98765 43210</small></span></a></section>
 <SectionHeading kicker="OCTOBER 11–19 · 2026" title={t.events} sub={t.eventsSub}/><section id="events" className="section nine-days"><div className="day-rail">{festival.map((d,i)=><button key={d.iso} className={activeDay===i?'active':''} onClick={()=>setActiveDay(i)}><small>DAY</small><b>{i+1}</b><span>{d.date}</span></button>)}</div><article className="day-stage"><div className="day-visual"><span>DAY {activeDay+1}</span><img src={`/img${activeDay%4+1}.jpg`} alt="Durga Devi decoration"/><div><Star/><p>{lang==='te'?'రోజువారీ అమ్మవారి రూపం':'Daily form of the Goddess'}</p><h3>{lang==='te'?festival[activeDay].te:festival[activeDay].deity}</h3></div></div><div className="day-details"><span className="date-pill"><CalendarDays/>{festival[activeDay].date}, 2026</span><h2>{lang==='te'?festival[activeDay].te:festival[activeDay].deity}</h2><div className="detail-card"><Sparkles/><span><small>{lang==='te'?'ప్రధాన పూజ':'MAIN PUJA'}</small><b>{lang==='te'?festival[activeDay].pujaTe:festival[activeDay].puja}</b><p>Morning 6:00 AM · Maha Harathi 7:00 PM</p></span></div><div className="detail-card fun"><Flower2/><span><small>{lang==='te'?'ఈ రోజు సరదా కార్యక్రమం':'TODAY’S FUN ACTIVITY'}</small><b>{lang==='te'?festival[activeDay].funTe:festival[activeDay].fun}</b><p>Village grounds · 5:00 PM</p></span></div>{activeDay>0&&<div className="yesterday"><span><Camera/> {lang==='te'?'నిన్నటి విశేషాలు':'Previous day highlights'}</span><p>{remoteUpdates.find(u=>u.festival_day===activeDay)?.summary||(lang==='te'?`${activeDay}వ రోజు పూజలు, ఆటలు మరియు హారతి విశేషాలు గ్యాలరీలో చూడండి.`:`See Day ${activeDay} puja, games and Harathi moments in the gallery.`)}</p><button onClick={()=>go('gallery')}>{lang==='te'?'చూడండి':'View highlights'}<ChevronRight/></button></div>}</div></article></section>
 <SectionHeading kicker="2025 ARCHIVE · గత సంవత్సరం" title={t.gallery} sub={t.gallerySub}/><section id="gallery" className="section"><div className="tabs">{['All','Photos','Videos'].map(v=><button className={galleryTab===v?'active':''} key={v} onClick={()=>setGalleryTab(v)}>{v}</button>)}</div><div className="gallery-grid">{filteredGallery.map((g,i)=><button className={`gallery-item g${i}`} key={g.src} onClick={()=>setLightbox(g)}>{g.type==='Videos'?<video muted preload="metadata" src={g.src}/>:<img src={g.src} alt={g.title}/>}<span className="gallery-shade"/><span className="year-badge">2025</span><span className="media-type">{g.type==='Videos'?<Play/>:<Camera/>}</span><span className="gallery-label"><b>{g.title}</b><small>2025 Highlights · Koragam</small></span></button>)}</div></section>
 <SectionHeading kicker="DEVOTEE DIRECTORY" title={t.gootra} sub={t.gootraSub}/><section id="donors" className="section donors"><div className="table-tools"><label><Search/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search name or gootram…"/></label><div><button onClick={()=>window.print()}><Download/>Export PDF</button><button onClick={exportDoc}><Download/>Export Word</button></div></div><div className="table-scroll"><table id="gootra-table"><thead><tr><th>S.No</th><th>Name (పేరు)</th><th>Gootram (గోత్రం)</th><th>Category</th><th>Phone</th></tr></thead><tbody>{filteredDonors.map(d=><tr key={d[0]}>{d.map((x,i)=><td key={x}>{i===3?<span className="category">{x}</span>:i===4?<a href={`tel:${x.replaceAll(' ','')}`}>{x}</a>:x}</td>)}</tr>)}</tbody></table></div></section>
 <section id="team" className="service-honours"><SectionHeading kicker="WITH GRATITUDE" title={t.committee} sub={t.committeeSub}/><div className="section honours-grid"><article><span><Sparkles/></span><small>{lang==='te'?'పంతులు గారు':'PRIEST SERVICES'}</small><h3>{lang==='te'?'మావుదూరి కృష్ణరావు గారు':'Mavuduri Krishna Rao Garu'}</h3><p>{lang==='te'?'అన్ని పవిత్ర పూజలు మరియు మంత్రోచ్చారణలకు అనుభవజ్ఞులైన పండితులు.':'Experienced priest guiding every sacred puja and mantra recitation.'}</p></article><article><span><Flower2/></span><small>{lang==='te'?'అలంకరణ సేవలు':'DECORATION SERVICES'}</small><h3>{lang==='te'?'డెకొరేషన్ & లైట్ సెట్టింగ్':'Decoration & Light Setting'}</h3><p>{lang==='te'?'అమ్మవారి అలంకరణ మరియు ఉత్సవ వేదిక రూపకల్పన.':'Ammavari decoration and festival-stage arrangements.'}</p></article><article><span><Lightbulb/></span><small>{lang==='te'?'లైటింగ్ సప్లైర్స్':'LIGHTING SUPPLIERS'}</small><h3>{lang==='te'?'అయ్యప్ప సప్లైర్స్':'Ayyappa Suppliers'}</h3><p>{lang==='te'?'ఉత్సవానికి లైటింగ్ మరియు ఎలక్ట్రికల్ సామగ్రి సేవలు.':'Festival lighting and electrical equipment services.'}</p></article></div></section>
 <section id="contact" className="contact-section"><div className="contact-copy"><span className="section-kicker">DARSHAN & DIRECTIONS</span><h2>{t.contact}</h2><p><MapPin/>Sri Durga Devi Temple, Koragam Village, Andhra Pradesh</p><p><Clock/>Morning 5:30–11:30 · Evening 5:00–9:30</p><div><a className="btn gold" href="https://maps.google.com/?q=Koragam+Andhra+Pradesh" target="_blank"><MapPin/>Get directions</a><a className="btn outline" href="tel:+919876543210"><Phone/>Call now</a></div></div><div className="map-card"><MapPin/><b>Koragam</b><span>Andhra Pradesh</span></div></section>
 <footer><div className="brand"><span className="brand-mark">శ్రీ</span><span><b>{t.brand}</b><small>{t.place}</small></span></div><p>© 2026 Sri Durga Devi Sharannavaratri Mahotsavam Committee</p><div><a href="#"><Facebook/></a><a href="#"><Instagram/></a><a href="#"><Video/></a></div></footer><nav className="bottom-nav"><button onClick={()=>go('home')}><Home/><span>Home</span></button><button onClick={()=>go('events')}><CalendarDays/><span>9 Days</span></button><button onClick={()=>go('gallery')}><ImageIcon/><span>2025</span></button><button onClick={()=>go('team')}><Users/><span>Team</span></button><button onClick={()=>go('contact')}><Phone/><span>Contact</span></button></nav>
 {lightbox&&<div className="modal lightbox" onClick={()=>setLightbox(null)}><button className="close"><X/></button><div onClick={e=>e.stopPropagation()}>{lightbox.type==='Videos'?<video controls autoPlay src={lightbox.src}/>:<img src={lightbox.src} alt={lightbox.title}/>}<div><span><b>{lightbox.title}</b><small>2025 Mahotsavam · Koragam</small></span><button onClick={share}><Share2/>Share</button></div></div></div>}</main>}
function SectionHeading({kicker,title,sub}:{kicker:string,title:string,sub:string}){return <div className="section-heading"><span>{kicker}</span><h2>{title}</h2><p>{sub}</p><i/></div>}
