'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {ArrowLeft,CheckCircle2,ImagePlus,LayoutDashboard,Loader2,LogIn,LogOut,Plus,Save,ShieldCheck,Trash2,Upload,Users,WalletCards,PartyPopper} from 'lucide-react';
import {AccountEntry,BhavaniMember,FestivalContent,GalleryItem,NightProgram,defaultFestivalContent,loadFestivalContent,saveFestivalSection,uploadFestivalMedia} from '@/backend/festival-content';
type Tab=keyof FestivalContent;
const tabs:{id:Tab;label:string;Icon:any;help:string}[]=[{id:'gallery',label:'Gallery',Icon:ImagePlus,help:'Add, edit or remove public gallery photos and videos.'},{id:'bhavani',label:'Bhavani Swamulu',Icon:Users,help:'Maintain the Bhavani Swamulu names and details.'},{id:'accounts',label:'Dussehra Accounts',Icon:WalletCards,help:'Add or edit account rows and amounts. The total updates automatically.'},{id:'nightPrograms',label:'Night Programs',Icon:PartyPopper,help:'Edit every night-after-puja cultural and games card.'}];
const uid=()=>`${Date.now()}-${Math.random().toString(36).slice(2,8)}`;
export default function AdminPage(){
 const [username,setUsername]=useState(''),[password,setPassword]=useState(''),[loading,setLoading]=useState(false),[session,setSession]=useState<boolean|null>(null),[tab,setTab]=useState<Tab>('gallery'),[status,setStatus]=useState('');
 const [content,setContent]=useState<FestivalContent>(defaultFestivalContent),[uploadingId,setUploadingId]=useState(''),[dirtySections,setDirtySections]=useState<Set<Tab>>(new Set());
 useEffect(()=>{loadFestivalContent().then(setContent);fetch('/api/admin/session').then(r=>r.json()).then(x=>setSession(Boolean(x.authenticated))).catch(()=>setSession(false))},[]);
 const login=async(e:React.FormEvent)=>{e.preventDefault();setLoading(true);setStatus('');try{const response=await fetch('/api/admin/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username,password})}),result=await response.json();if(!response.ok)throw new Error(result.error);setSession(true)}catch(e:any){setStatus(e.message||'Login failed.')}finally{setLoading(false)}};
 const logout=async()=>{await fetch('/api/admin/login',{method:'DELETE'});setSession(false);setPassword('')};
 const markDirty=(section:Tab)=>setDirtySections(old=>new Set(old).add(section));
 const update=<K extends Tab>(section:K,id:string,patch:Partial<FestivalContent[K][number]>)=>{markDirty(section);setStatus('Unsaved changes — click Save changes to update the public website.');setContent(old=>({...old,[section]:old[section].map((item:any)=>item.id===id?{...item,...patch}:item)}))};
 const remove=(section:Tab,id:string)=>{if(confirm('Delete this item? The public website changes only after you click Save changes.')){markDirty(section);setStatus('Item removed. Click Save changes to publish.');setContent(old=>({...old,[section]:old[section].filter((item:any)=>item.id!==id)}))}};
 const add=()=>{markDirty(tab);setStatus('New item added. Complete its details, then click Save changes.');setContent(old=>{const additions:Record<Tab,any>={gallery:{id:uid(),src:'',type:'Images',title:'New gallery item',description:'',highlight:true} as GalleryItem,bhavani:{id:uid(),name:'New member',details:'Devotional seva',photo:'/images/avatars/default-avatar.svg'} as BhavaniMember,accounts:{id:uid(),label:'2026',labelTe:'2026',amount:0} as AccountEntry,nightPrograms:{id:uid(),day:`DAY ${String(old.nightPrograms.length+1).padStart(2,'0')}`,date:'OCT 20',title:'New Program',titleTe:'కొత్త కార్యక్రమం',desc:'Program description',descTe:'కార్యక్రమ వివరణ',image:'/images/backgrounds/night-festival-2026.png'} as NightProgram};return {...old,[tab]:[...old[tab],additions[tab]]}})};
 const publish=async()=>{setLoading(true);setStatus('Saving and updating the public website…');try{await saveFestivalSection(tab,content[tab] as any);setDirtySections(old=>{const next=new Set(old);next.delete(tab);return next});setStatus('Saved successfully — all visitor dashboards are now updated.')}catch(e:any){setStatus(e.message||'Unable to save changes.')}finally{setLoading(false)}};
 const upload=async(id:string,file?:File)=>{if(!file)return;setUploadingId(id);setStatus('Uploading media…');try{const folder=tab==='gallery'?'gallery':tab==='bhavani'?'bhavani-profiles':'night-programs',url=await uploadFestivalMedia(file,folder);if(tab==='gallery')update('gallery',id,{src:url,type:file.type.startsWith('video/')?'Videos':'Images'});else if(tab==='bhavani')update('bhavani',id,{photo:url});else update('nightPrograms',id,{image:url});setStatus('Upload complete. Click Save changes to update all visitors.')}catch(e:any){setStatus(e.message)}finally{setUploadingId('')}};
 if(session===null)return <main className="admin-login"><Loader2 className="spin"/></main>;
 if(!session)return <main className="admin-login"><Link href="/"><ArrowLeft/>Back to website</Link><section><span><ShieldCheck/></span><p>2026 ORGANIZER PORTAL</p><h1>Temple Administration</h1><small>Enter the authorized administrator username and password.</small><form onSubmit={login}><label>Username<input autoComplete="username" required value={username} onChange={e=>setUsername(e.target.value)} placeholder="Username"/></label><label>Password<input type="password" autoComplete="current-password" required value={password} onChange={e=>setPassword(e.target.value)} placeholder="Password"/></label><button disabled={loading}>{loading?<Loader2 className="spin"/>:<LogIn/>}{loading?'Signing in…':'Sign in'}</button></form>{status&&<p className="admin-login-error">{status}</p>}<em>Only authorized festival committee administrators can continue.</em></section></main>;
 const current=tabs.find(x=>x.id===tab)!;
 return <main className="admin-shell"><aside><Link className="admin-brand" href="/"><span>శ్రీ</span><b>Durga Devi<br/><small>2026 ADMIN</small></b></Link><nav><button><LayoutDashboard/>Content Dashboard</button>{tabs.map(({id,label,Icon})=><button key={id} className={tab===id?'active':''} onClick={()=>{setTab(id);setStatus(dirtySections.has(id)?'Unsaved changes — click Save changes to update the public website.':'')}}><Icon/>{label}{dirtySections.has(id)&&<i className="admin-unsaved-dot"/>}</button>)}</nav><button onClick={logout}><LogOut/>Sign out</button></aside><div className="admin-main"><header><div><p>OCTOBER 11–20 · 2026</p><h1>Festival Content Dashboard</h1></div><span><i/>Shared publishing</span></header><div className="admin-stats"><article><ImagePlus/><span><small>Gallery media</small><b>{content.gallery.length}</b></span></article><article><Users/><span><small>Bhavani Swamulu</small><b>{content.bhavani.length}</b></span></article><article><WalletCards/><span><small>Accounts total</small><b>₹{content.accounts.reduce((n,x)=>n+Number(x.amount||0),0).toLocaleString('en-IN')}</b></span></article></div><section className="admin-panel"><div className="admin-tabs">{tabs.map(x=><button key={x.id} onClick={()=>{setTab(x.id);setStatus(dirtySections.has(x.id)?'Unsaved changes — click Save changes to update the public website.':'')}} className={tab===x.id?'active':''}>{x.label}{dirtySections.has(x.id)&&<i className="admin-unsaved-dot"/>}</button>)}</div><div className="admin-crud-guide"><span><b>1</b><strong>Add</strong><small>Create a new row or card</small></span><span><b>2</b><strong>Edit / Upload</strong><small>Update text, amount or media</small></span><span><b>3</b><strong>Save changes</strong><small>Publish instantly for visitors</small></span></div><div className="admin-toolbar"><div><h2>{current.label}</h2><p>{current.help}</p>{dirtySections.has(tab)&&<em className="admin-unsaved"><i/>Unsaved changes</em>}</div><span className="admin-actions"><button onClick={add}><Plus/>Add item</button><button onClick={publish} disabled={loading||!dirtySections.has(tab)}><Save/>{loading?'Saving…':'Save changes'}</button></span></div><div className="admin-crud-list">
 {tab==='gallery'&&content.gallery.map(item=><article className="admin-crud-card" key={item.id}><div className="admin-media-preview">{item.src?(item.type==='Videos'?<video src={item.src} muted/>:<img src={item.src} alt="" onError={e=>{e.currentTarget.src='/images/avatars/default-avatar.svg'}}/>):<ImagePlus/>}</div><div className="admin-field-grid"><label>Title<input value={item.title} onChange={e=>update('gallery',item.id,{title:e.target.value})}/></label><label>Type<select value={item.type} onChange={e=>update('gallery',item.id,{type:e.target.value as GalleryItem['type']})}><option>Images</option><option>Videos</option></select></label><label className="wide">Description<textarea value={item.description} onChange={e=>update('gallery',item.id,{description:e.target.value})}/></label><label className="wide">Media URL<input key={item.src} defaultValue={item.src} onBlur={e=>{if(e.target.value!==item.src)update('gallery',item.id,{src:e.target.value.trim()})}} placeholder="/image.jpg or https://…"/></label><label className="admin-file"><Upload/>{uploadingId===item.id?'Uploading…':'Upload image/video'}<input type="file" accept="image/*,video/*" onChange={e=>upload(item.id,e.target.files?.[0])}/></label><label className="admin-check"><input type="checkbox" checked={item.highlight} onChange={e=>update('gallery',item.id,{highlight:e.target.checked})}/>2025 highlight</label></div><button className="admin-delete" onClick={()=>remove('gallery',item.id)}><Trash2/>Delete</button></article>)}
 {tab==='bhavani'&&content.bhavani.map(item=><article className="admin-crud-card compact" key={item.id}><div className="admin-avatar-preview"><img src={item.photo||'/images/avatars/default-avatar.svg'} alt={item.name} onError={e=>{e.currentTarget.src='/images/avatars/default-avatar.svg'}}/></div><div className="admin-field-grid"><label>Name<input value={item.name} onChange={e=>update('bhavani',item.id,{name:e.target.value})}/></label><label>Details<input value={item.details} onChange={e=>update('bhavani',item.id,{details:e.target.value})}/></label><label className="wide">Profile image URL<input key={item.photo} defaultValue={item.photo} onBlur={e=>{if(e.target.value!==item.photo)update('bhavani',item.id,{photo:e.target.value.trim()||'/images/avatars/default-avatar.svg'})}} placeholder="/images/avatars/default-avatar.svg or https://…"/></label><label className="admin-file wide"><Upload/>{uploadingId===item.id?'Uploading…':'Upload profile image'}<input type="file" accept="image/*" onChange={e=>upload(item.id,e.target.files?.[0])}/></label></div><button className="admin-delete" onClick={()=>remove('bhavani',item.id)}><Trash2/>Delete</button></article>)}
 {tab==='accounts'&&content.accounts.map((item,i)=><article className="admin-crud-card compact" key={item.id}><div className="admin-row-number">{String(i+1).padStart(2,'0')}</div><div className="admin-field-grid three"><label>English label<input value={item.label} onChange={e=>update('accounts',item.id,{label:e.target.value})}/></label><label>Telugu label<input value={item.labelTe} onChange={e=>update('accounts',item.id,{labelTe:e.target.value})}/></label><label>Amount (₹)<input type="number" min="0" value={item.amount} onChange={e=>update('accounts',item.id,{amount:Number(e.target.value)})}/></label></div><button className="admin-delete" onClick={()=>remove('accounts',item.id)}><Trash2/>Delete</button></article>)}
 {tab==='nightPrograms'&&content.nightPrograms.map(item=><article className="admin-crud-card" key={item.id}><div className="admin-media-preview"><img src={item.image} alt="" onError={e=>{e.currentTarget.src='/images/avatars/default-avatar.svg'}}/></div><div className="admin-field-grid"><label>Day<input value={item.day} onChange={e=>update('nightPrograms',item.id,{day:e.target.value})}/></label><label>Date<input value={item.date} onChange={e=>update('nightPrograms',item.id,{date:e.target.value})}/></label><label>English title<input value={item.title} onChange={e=>update('nightPrograms',item.id,{title:e.target.value})}/></label><label>Telugu title<input value={item.titleTe} onChange={e=>update('nightPrograms',item.id,{titleTe:e.target.value})}/></label><label className="wide">English description<textarea value={item.desc} onChange={e=>update('nightPrograms',item.id,{desc:e.target.value})}/></label><label className="wide">Telugu description<textarea value={item.descTe} onChange={e=>update('nightPrograms',item.id,{descTe:e.target.value})}/></label><label className="wide">Image URL<input key={item.image} defaultValue={item.image} onBlur={e=>{if(e.target.value!==item.image)update('nightPrograms',item.id,{image:e.target.value.trim()})}}/></label><label className="admin-file"><Upload/>{uploadingId===item.id?'Uploading…':'Upload card image'}<input type="file" accept="image/*" onChange={e=>upload(item.id,e.target.files?.[0])}/></label></div><button className="admin-delete" onClick={()=>remove('nightPrograms',item.id)}><Trash2/>Delete</button></article>)}
 </div>{status&&<p className={`admin-note ${status.startsWith('Saved successfully')?'success':''}`}>{status.startsWith('Saved successfully')&&<CheckCircle2/>}{status}</p>}</section>{dirtySections.has(tab)&&<div className="admin-save-dock"><span><b>Unsaved changes</b><small>Save to update all visitor dashboards</small></span><button onClick={publish} disabled={loading}><Save/>{loading?'Saving…':'Save changes'}</button></div>}<p className="admin-note">Changes are shared through Neon PostgreSQL when <b>DATABASE_URL</b> is configured. Local uploads remain available from this server.</p></div></main>;
}
