create table if not exists festival_content (
  section text primary key check (section in ('gallery','bhavani','accounts','nightPrograms')),
  payload jsonb not null default '[]'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists payment_receipts (
  id bigint generated by default as identity primary key,
  public_reference text unique not null,
  donor_name text not null,
  mobile text not null,
  amount numeric(10,2) not null check (amount > 0 and amount <= 100000),
  utr text,
  status text not null default 'pending' check (status in ('pending','verified','rejected')),
  created_at timestamptz not null default now()
);

create index if not exists payment_receipts_status_created_idx
  on payment_receipts(status,created_at desc);
